-- T-SQL Initialization script for Azure SQL Database

-- Create Core Tables for the Platform

-- 1. Users / Team Members Table
CREATE TABLE TeamMembers (
    Id UNIQUEIDENTIFIER DEFAULT NEWID() PRIMARY KEY,
    Email NVARCHAR(255) NOT NULL UNIQUE,
    FullName NVARCHAR(255) NOT NULL,
    Role NVARCHAR(50) NOT NULL,
    CreatedAt DATETIME2 DEFAULT SYSUTCDATETIME()
);
GO

-- 2. Clients Table
CREATE TABLE Clients (
    Id UNIQUEIDENTIFIER DEFAULT NEWID() PRIMARY KEY,
    Name NVARCHAR(255) NOT NULL,
    Industry NVARCHAR(100),
    CreatedAt DATETIME2 DEFAULT SYSUTCDATETIME()
);
GO

-- 3. Projects Table
CREATE TABLE Projects (
    Id UNIQUEIDENTIFIER DEFAULT NEWID() PRIMARY KEY,
    ClientId UNIQUEIDENTIFIER NOT NULL FOREIGN KEY REFERENCES Clients(Id),
    Name NVARCHAR(255) NOT NULL,
    Status NVARCHAR(50) DEFAULT 'Draft',
    CreatedAt DATETIME2 DEFAULT SYSUTCDATETIME()
);
GO

-- 4. Deliverables Table
CREATE TABLE Deliverables (
    Id UNIQUEIDENTIFIER DEFAULT NEWID() PRIMARY KEY,
    ProjectId UNIQUEIDENTIFIER NOT NULL FOREIGN KEY REFERENCES Projects(Id),
    DeliverableType NVARCHAR(100) NOT NULL,
    Title NVARCHAR(255) NOT NULL,
    Status NVARCHAR(50) DEFAULT 'Draft',
    FileName NVARCHAR(255),
    FileUrl NVARCHAR(2000),
    CreatedAt DATETIME2 DEFAULT SYSUTCDATETIME()
);
GO
